### ISSUE TITLE
UI Prototype

### ISSUE THREAD

**Issue by mesaisl** [mathiastr/SE2_Di4_Coup#2]
UI Prototype erstellen.

**Comment by Ario98** [comment]
Mögliche Anordnung der Aktivitäten. Aktivitäten mit blauer Farbe sind optional.

<img width="759" alt="Bildschirmfoto 2020-04-18 um 18 39 48" src="https://user-images.githubusercontent.com/58989295/79786385-aa37ff00-8345-11ea-8c18-ce5e568894b7.png">

UI-Prototyp:
![presentation1](https://user-images.githubusercontent.com/58989295/79786522-e3706f00-8345-11ea-9727-d8e12f92c63c.png)

Karten:
![presentation2](https://user-images.githubusercontent.com/58989295/79786535-e9665000-8345-11ea-8858-126fb027d94d.png)
